<?php

/**
 * @file
 * Contains flinkevents.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function flinkevents_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the flinkevents module.
    case 'help.page.flinkevents':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module will be able to handle events and subscriptions to them') . '</p>';
      return $output;

    default:
  }
}

